name: Automerge PR
on:
  pull_request_target:
    paths:
      - "zones/*.yaml"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR
        uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
          fetch-depth: 0

      - name: Fetch main repo
        run: |
          git remote add upstream https://github.com/Olivr/free-domain.git
          git fetch upstream
      - name: Auto-merge
        uses: "pascalgn/automerge-action@v0.14.2"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_METHOD: "squash"
          MERGE_COMMIT_MESSAGE: "pull-request-title"
          MERGE_DELETE_BRANCH: true
          UPDATE_METHOD: "rebase"
          MERGE_LABELS: ""
